#****************************************************
# The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
# "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and
# "OPTIONAL" in this document are to be interpreted as described in BCP
# 14 [RFC2119] [RFC8174] when, and only when, they appear in all
# capitals
#****************************************************

openapi: 3.0.0
info:
  version: 0.0.7
  title: LoRaWAN NS-GW NS controlplane interface
  description: LoRaWAN NS-GW_Interface, NS Interfacce

servers:
# Added by API Auto Mocking Plugin
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/JOACHIMERNST61_1/ns_gw_ns/0.0.7


paths:
  /r:
    put:
      description: |
        registration of GW at NS. 
      requestBody:
        description: |
          Request body MUST contain the objects GwIdentity, GwProfile, and Uptime. 
          Regisration request is sent after successfull set up of as WSS connection from GW to NS.
          Depending on GW state, the NS MAY use different strategies to learn capabilities and
          allign configurations. 
        required: true
        content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/ObjectsPutableToNsRegistration'
            application/json:
              schema: 
                $ref: '#/components/schemas/ObjectsPutableToNsRegistration'
      responses:
        '201':
          description: Successfull Registration of the GW, NS resources created
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/ObjectsResponseableToPutToNsRegistration'
        '204':
          description: Successfull Re-Registration of the GW, NS resources updated
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/ObjectsResponseableToPutToNsRegistration'
        '400':
          description: Bad request
          
  /{gwEui}/d:
    delete:
      description: |
        De-registration initiated by GW at NS.
        No query parameters and no requestBody are used for this request.
      parameters:
        - $ref: '#/components/parameters/gwEui'
      responses:
        '202':
          description: De-Registration at gw successfull, GW in commissioned state
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/GwIdentityResponse'
        '400':
          description: De-Registrering at GW failed.

  /{gwEui}/c:
    parameters:
    - $ref: '#/components/parameters/gwEui'
    get:
      description: any configuration data the GW may requested at the NS
      parameters:
        - $ref: '#/components/parameters/qParameter'
      responses:
        '200':
          description: success, to do details later
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/ObjectsGetableFromNsConfiguration'
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectsGetableFromNsConfiguration'
        '400':
          description: any failure, no content
    put:
      description: any configuration data the GW pushes to the NS
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              $ref: '#/components/schemas/ObjectsPutableToNSConfiguration'
          application/json:
            schema:
              $ref: '#/components/schemas/ObjectsPutableToNSConfiguration'
      responses:
        '202':
          description: success
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/ObjectsResponseableToPutToNsConfiguration'
        '400':
          description: error case
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/ObjectsResponseableToPutToNsConfiguration'

  /{gwEui}/s:
    parameters:
    - $ref: '#/components/parameters/gwEui'
    description: periodic statistic and status data
    post:
      description: periodic statistic and status data
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              $ref: '#/components/schemas/ObjectsPostableToNsStatistics'
          application/json:
            schema:
               $ref: '#/components/schemas/ObjectsPostableToNsStatistics'
      responses:
        '202':
          description: success
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/ObjectsResponseableToPostToNsStatistics'
        '400':
          description: error case
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/ObjectsResponseableToPostToNsStatistics'      

  /{gwEui}/a:
    parameters:
    - $ref: '#/components/parameters/gwEui'
    post:
      description: any configuration data the GW pushes to the NS
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              $ref: '#/components/schemas/ObjectsPostableToNsAsync'
          application/json:
            schema:
              $ref: '#/components/schemas/ObjectsPostableToNsAsync'
      responses:
        '202':
          description: success
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/Success'
        '400':
          description: error case
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/Failure'
                
components:
  parameters:
    qParameter:
      description: todo
      in: query
      name: qParameter
      required: false
      schema:
        type: string
    objectIdPath:
      description: Path param specifying Obj
      in: path
      name: objectIdPath
      required: true
      schema: 
        type: integer
    gwIndentityPath:
      description: Path parameter for gw_identity, as defined in proto file
      in: path
      name: gwIdentityPath
      required: true
      schema:
        type: integer
    gwEui:
      name: gwEui
      in: path
      required: true
      schema:
        type: integer
      description: todo
        
  schemas:
    ObjectsPutableToNsRegistration:
      description: objects supported in PUT request from GW to NS.
      anyOf:
        - $ref: '#/components/schemas/GwIdentity'
        - $ref: '#/components/schemas/GwProfile'
        - $ref: '#/components/schemas/Uptime'
        - $ref: '#/components/schemas/Inventory'
        - $ref: '#/components/schemas/Versions'
        - $ref: '#/components/schemas/RadioUnitCapabilities'
        - $ref: '#/components/schemas/RadioUnitsListCapabilities'
        - $ref: '#/components/schemas/AntennaCapabilities'
        - $ref: '#/components/schemas/AntennasListCapabilities'
    ObjectsResponseableToPutToNsRegistration:
      description: objects supported in PUT Response from NS to GW.
      anyOf:
        - $ref: '#/components/schemas/GwIdentityResponse'
        - $ref: '#/components/schemas/GwProfileResponse'
        - $ref: '#/components/schemas/TimeInfo'
        - $ref: '#/components/schemas/Success'
        - $ref: '#/components/schemas/Failure'
    ObjectsPutableToNSConfiguration:
      description: configuration objects the GW may send to the NS
      anyOf:
        - $ref: '#/components/schemas/RegionOfOperationConfig'
        - $ref: '#/components/schemas/RadioUnitsListConfig'
        - $ref: '#/components/schemas/RadioUnitConfig'
        - $ref: '#/components/schemas/AntennasListConfig'
        - $ref: '#/components/schemas/AntennaConfig'     
        - $ref: '#/components/schemas/DataRateTableConfig'
        - $ref: '#/components/schemas/ChannelConfig'
    ObjectsResponseableToPutToNsConfiguration:
      description: objects the NS may use for responding to putted configuration
      anyOf:
        - $ref: '#/components/schemas/Success'
        - $ref: '#/components/schemas/Failure'
    ObjectsGetableFromNsConfiguration:
      description: objects which may be requested by GET request at NS.
      anyOf:
        - $ref: '#/components/schemas/RegionOfOperationConfig'
        - $ref: '#/components/schemas/RadioUnitsListConfig'
        - $ref: '#/components/schemas/RadioUnitConfig'
        - $ref: '#/components/schemas/AntennasListConfig'
        - $ref: '#/components/schemas/AntennaConfig'
        - $ref: '#/components/schemas/DataRateTableConfig'
        - $ref: '#/components/schemas/ChannelConfig'
    ObjectsPostableToNsStatistics:
      description: objects which may be posted to NS statistics.
      anyOf:
        - $ref: '#/components/schemas/Any'
    ObjectsResponseableToPostToNsStatistics:
      description: objects which may be posted to NS statistics.
      anyOf:
        - $ref: '#/components/schemas/Any'    
    ObjectsPostableToNsAsync:
      description: objects being posted asynchronously from GW to NS like Alarms, State changes
      anyOf:
        - $ref: '#/components/schemas/RadioUnitEvent'
    ObjectsResponseableToPostToNsAsync:
      description: objects which may be posted to NS statistics.
      anyOf:
        - $ref: '#/components/schemas/Any'    
    Any:
      #placeholder for further work 
      type: object
    Success:
      type: object
    Failure:
      type: object
    GwIdentity:
      type: object
    GwIdentityResponse:
      type: object
    GwProfile:
      type: object
    GwProfileResponse:
      type: object
    Uptime:
      type: object
    TimeInfo:
      type: object
    Inventory:
      type: object
    Versions:
      type: object
    RegionOfOperationConfig:
      type: object
    RadioUnitCapabilities:
      type: object
    RadioUnitsListCapabilities:
      type: object
    RadioUnitConfig:
      type: object
    RadioUnitsListConfig:
      type: object
    RadioUnitEvent:
      type: object
    AntennaCapabilities:
      type: object
    AntennaConfig:
      type: object
    DataRateTableConfig:
      type: object
    ChannelConfig:
      type: object
      
