openapi: 3.0.0
info:
  version: 0.0.7
  title: LoRaWAN GW Interface
  description: LoRaWAN NS-GW_Interface, GW Interface

servers:
# Placeholder for actual GW Interface
- url: 'https://virtualserver.swaggerhub.com/tbejer/LorawanGw/0.0.7'

paths:
  /c:
    get:
      description: |
        Retrieve ObjectIndex or specific list of objects from a device
      parameters:
      - $ref: '#/components/parameters/qOption'
      responses:
        '205':
          description: |
            Successful return of requested Objects or ObjectIndex etc...
          content:
            application/octet-stream:
              schema:
                oneOf:
                - $ref: 'https://api.swaggerhub.com/domains/tbejer/etc'
                - $ref: 'https://api.swaggerhub.com/domains/tbejer/etc'
        '400':
          description: Bad Request.
        '401':
          description: Unauthorized.
        '402':
          description: Bad Option.
        '403':
          description: Object not found, response won't fit in MTU.
    put:
      description: gw configuration put messages from ns.
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              $ref:'https://api.swaggerhub.com/domains/tbejer.etc'
      responses:
        '202':
          description: Objects have been updated.
        '400':
          description: Bad Request.

  /c/{objectIdPath}:
    get:
      description: | 
        Retrieve objects from GW.
      parameters:
      - $ref: '#/components/parameters/objectIdPath'
      - $ref: '#/components/parameters/fOption'
      responses:
        '200':
          description: Success

#
# Query parameters used for gateway requests
#
components:
  parameters:
    qOption:
      description: |
        todo
      in: query
      name: q
      required: false
      schema:
        type: object
        description: list of requested objects
    fOption:
      description: |
        F option for request to device will retrieve full table content, while leaving the
        F option will only retrieve the table ID, label and version
      in: query
      name: f
      required: false
      schema:
        type: boolean
        description: default is false.
        
    objectIdPath:
      description: Path param specifying TLV ID.
      in: path
      name: objectIdPath
      required: true 
      schema:
        type: integer