# https://app.swaggerhub.com/apis/JOACHIMERNST61_1/LoRaNSGW_Commons/0.0.7
openapi: 3.0.0
info:
  version: 0.0.7
  title: LoRaNSGW_Commons
  description: |
    Common components on LoraWAN NS-GW Interface
    https://virtserver.swaggerhub.com/JOACHIMERNST61_1/LoRaNSGW_Commons/0.0.7

components:
  schemas:
    ObjectsGetAbleFromGW:
      description: |
        Objects that are GET-able from a GW through a url <gw-url>/c.
      anyOf:
        - $ref: '#/components/schemas/ObjectIndex'
        - $ref: '#/components/schemas/GwIdentity'
        - $ref: '#/components/schemas/GwProfile'
        - $ref: '#/components/schemas/Uptime'
        - $ref: '#/components/schemas/Versions'
        - $ref: '#/components/schemas/Inventory'
        - $ref: '#/components/schemas/RegionOfOperationConfig'
        - $ref: '#/components/schemas/RadioUnits'
        - $ref: '#/components/schemas/RadioUnitCapabilities'
        - $ref: '#/components/schemas/RadioUnitConfig'
        - $ref: '#/components/schemas/Antennas'
        - $ref: '#/components/schemas/AntennaCapabilities'
        - $ref: '#/components/schemas/AntennaConfig'
        - $ref: '#/components/schemas/DataRateTableConfig'
        - $ref: '#/components/schemas/ChannelConfig'

    #
    # Object placeholders to allow OpenAPI to compile.
    # Each of these is authoritatively defined in
    # the CSMP .proto file.
    #
    
    ObjectsPutableToNSRegisration:
      description: |
        objects being PUT-able to <ns-uri>/<gweui>/r
        GWIdentity, GWProfile, and Uptime are required.
        Others MAY be sent; strategy MAY depend on GW state.
      anyOf:
        - $ref: '#/components/schemas/GwIdentity'
        - $ref: '#/components/schemas/GwProfile'
        - $ref: '#/omponents/schemas/Uptime'
        - $ref: '#/components/schemas/Versions'
        - $ref: '#/components/schemas/Inventory'
        - $ref: '#/components/schemas/RegionOfOPerationConfig'
        - $ref: '#/components/schemas/RadioUnits'
        - $ref: '#/components/schemas/RadioUnitCapabilities'
        - $ref: '#/components/schemas/Antennas'
        - $ref: '#/components/schemas/AntennaCapabilities'

    ObjectsOnRegistrationDeleteResponse:
      description: |
        Objectes allowed in delete response on registration resoure r
      anyOf:
        -ref$: '#/components/schemas/GwIdentityResponse'
        -ref$: '#/components/schemas/RegionOfOperationResponse'
        
    ObjectsOnRegistrationResponse:
      description: |
        objects allowed in registration response
      anyOf:
        - $ref: '#/components/schemas/GwIdentityResponse'
        - $ref: '#/components/schemas/GwProfileResponse'
        - $ref: '#/components/schemas/TimingInfo'
        - $ref: '#/components/schemas/RegionOfOperationResponse'

    ObjectsGetableAtNs:
      description: |
        objects for configuration that the GW MAY request at the NS.
      anyOf:
        - $ref: '#/components/schemas/RadioUnits'
        - $ref: '#/components/schemas/RadioUnitConfig'
        - $ref: '#/components/schemas/Antennas'
        - $ref: '#/components/schemas/AntennaConfig'
        - $ref: '#/components/schemas/DataRateTableConfig'
        - $ref: '#/components/schemas/ChannelConfig'      
        
    ObjectsPutAbleToNSConfiguration:
      description: |
        objects being PUT-able to <ns-uri>/<deveui>/c
      anyOf:
        - $ref: '#/components/schemas/RadioUnits'
        - $ref: '#/components/schemas/RadioUnitConfig'
        - $ref: '#/components/schemas/Antennas'
        - $ref: '#/components/schemas/AntennaConfig'
        - $ref: '#/components/schemas/DataRateTableConfig'
        - $ref: '#/components/schemas/ChannelConfig'      
    
    ObjectIndex:
      type: object
    GwIdentity:
      type: object
    GwIdentityResponse:
      type: object
    GwProfile:
      type: object
    GwProfileResponse:
      type: object
    Uptime:
      type: object
    TimingInfo:
      type: object
    Versions:
      type: object
    Inventory:
      type: object
    RegionOfOperationConfig:
      type: object
    RegionOfOperationResponse:
      type: object
    RadioUnits:
      type: object
    RadioUnitCapability:
      type: object
    RadioUnitConfiguration:
      type: object
    Antennas:
      type: object
    AntennaCapabilities:
      type: object
    AntennaConfig:
      type: object
    

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/JOACHIMERNST61_1/LoRaNSGW_Commons/0.0.7
