# https://app.swaggerhub.com/apis/JOACHIMERNST61_1/ns_gw_ns/0.0.7
openapi: 3.0.0
info:
  version: 0.0.7
  title: LoRaWAN NSGW_NS
  description: LoRaWAN NS-GW_Interface, NS Interfacce

servers:
# Added by API Auto Mocking Plugin
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/JOACHIMERNST61_1/ns_gw_ns/0.0.7


paths:
  /r:
    put:
      description: |
        registration of GW at NS. 
      requestBody:
        description: |
          Request body MUST contain the objects GwIdentity, GwProfile, and Uptime.
        required: true
        content:
            application/octet-stream:
              schema:
#                $ref: 'https://app.swaggerhub.com/apis/JOACHIMERNST61_1/LoRaNSGW_Commons/0.0.7#/components/schemas/ObjectsPutableToNSRegisration'
                $ref: '#/components/schemas/ObjectsPutableToNSRegisration'
            application/json:
              schema: 
                $ref: '#/components/schemas/ObjectsPutableToNSRegistration_json'
      responses:
        '202':
          description: Successfull Registration of the GW
          content:
            application/octet-stream:
              schema:
#                $ref: 'https://app.swaggerhub.com/apis/JOACHIMERNST61_1/LoRaNSGW_Commons/0.0.7#/components/schemas/ObjectsResponsAbleToNSRegisration'
                $ref: '#/components/schemas/ObjectsResponsableToNSRegisration'
        '400':
          description: Bad request
          
  /{gwEui}/r/{gwIdentityPath}:
    delete:
      description: |
        De-registration initiated by GW at NS.
      responses:
        '202':
          description: De-Registration at gw successfull, GW in commissioned state
          content:
            application/octet-stream:
              schema:
#                $ref: 'https://app.swaggerhub.com/apis/JOACHIMERNST61_1/LoRaNSGW_Commons/0.0.7#/components/schemas/GwIdentityResponse'
                $ref: '#/components/schemas/GwIdentityResponse'
        '400':
          description: De-Registrering at GW failed.
          
  /{gwEui}/c:
    get:
      description: any configuration data the GW may requested at the NS.
      responses:
        '200':
          description: success
          content:
            application/octet-stream:
              schema:
                $ref: 'https://app.swaggerhub.com/apis/JOACHIMERNST61_1/LoRaNSGW_Commons/0.0.7#/components/schemas/ObjectsGetableAtNs'
        '400':
          description: any failure, no content
    put:
        description: any configuration data the GW pushes to the NS
        requestBody:
          required: true
          content:
            application/octet-stream:
              schema:
                $ref: 'https://app.swaggerhub.com/apis/JOACHIMERNST61_1/LoRaNSGW_Commons/0.0.7#/components/schemas/ObjectsPutAbleToNSRegisration'
        responses:
          '202':
            description: success
            content:
              application/octet-stream:
                schema:
                  $ref: 'https://app.swaggerhub.com/apis/JOACHIMERNST61_1/LoRaNSGW_Commons/0.0.7#/components/schemas/ObjectsResponsAbleToNSConfiguration'
          '400':
            description: error case
            content:
              application/octet-stream:
                schema:
                  $ref: 'https://app.swaggerhub.com/apis/JOACHIMERNST61_1/LoRaNSGW_Commons/0.0.7#/components/schemas/ObjectsResponsAbleToNSConfiguration'

  /{gwEui}/s:
    description: periodic statistic and status data
    post:
      description: periodic statistic and status data
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              $ref: 'https://app.swaggerhub.com/apis/JOACHIMERNST61_1/LoRaNSGW_Commons/0.0.7#/components/schemas/ObjectsPutAbleToNSRegisration'
      responses:
        '202':
          description: success
          content:
            application/octet-stream:
              schema:
                $ref: 'https://app.swaggerhub.com/apis/JOACHIMERNST61_1/LoRaNSGW_Commons/0.0.7#/components/schemas/ObjectsResponsAbleToNSConfiguration'
        '400':
          description: error case
          content:
            application/octet-stream:
              schema:
                $ref: 'https://app.swaggerhub.com/apis/JOACHIMERNST61_1/LoRaNSGW_Commons/0.0.7#/components/schemas/ObjectsResponsAbleToNSConfiguration'      

  /{gwEui}/a:
    description: any aynchronous events, state changes, and alarms
    post:
      description: any configuration data the GW pushes to the NS
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              $ref: 'https://app.swaggerhub.com/apis/JOACHIMERNST61_1/LoRaNSGW_Commons/0.0.7#/components/schemas/ObjectsPutAbleToNSRegisration'
      responses:
        '202':
          description: success
          content:
            application/octet-stream:
              schema:
                $ref: 'https://app.swaggerhub.com/apis/JOACHIMERNST61_1/LoRaNSGW_Commons/0.0.7#/components/schemas/ObjectsResponsAbleToNSConfiguration'
        '400':
          description: error case
          content:
            application/octet-stream:
              schema:
                $ref: 'https://app.swaggerhub.com/apis/JOACHIMERNST61_1/LoRaNSGW_Commons/0.0.7#/components/schemas/ObjectsResponsAbleToNSConfiguration'
                
components:
  parameters:
    objectIdPath:
      description: Path param specifying Obj
      in: path
      name: objectIdPath
      required: true
      schema: 
        type: integer
    gwIndentityPath:
      description: Path parameter for gw_identity, as defined in proto file
      in: path
      name: gwIdentityPath
      required: true
      schema:
        type: integer
    gwRegionalizationPath:
      description: Path parametr for Regionalization
      in: path
      name: gwRegionalizationPath
      required: true
      schema:
        type: integer
    gwEui:
      description: todo
      name: gwEUI 
      in: path
      required: true
      schema:
        type: integer
        
  schemas:
    ObjectsPutableToNSRegisration:
      description: objects supported in PUT request from GW to NS.
      anyOf:
        - $ref: '#/components/schemas/GwIdentity'
        - $ref: '#/components/schemas/GwProfile'
        - $ref: '#/components/schemas/Uptime'
        - $ref: '#/components/schemas/Inventory'
        - $ref: '#/components/schemas/Versions'
        - $ref: '#/components/schemas/RadioUnitCapabilities'
        - $ref: '#/components/schemas/AntennaCapabilities'
    ObjectsPutableToNSRegistration_json:
      description: |
        JSON is for documentation purposes only, do not use in implementation.
        Use objects as defined in "ObjectsPutableToNSRegistration" instead.
      type: array
      items: 
        type: string
        enum: 
         - GwIdentity
         - GwProfile
         - Uptime
         - Inventory
         - Versions
         - RadioUnitCapabilities
         - AntennaCapabilities
    ObjectsResponsableToNSRegisration:
      description: objects supported in PUT Response from NS to GW.
      anyOf:
        - $ref: '#/components/schemas/GwIdentityResponse'
        - $ref: '#/components/schemas/GwProfileResponse'
        - $ref: '#/components/schemas/TimeInfo'
        - $ref: '#/components/schemas/Success'
        - $ref: '#/components/schemas/Failure'
  
    Success:
      type: object
    Failure:
      type: object
    GwIdentity:
      type: object
    GwIdentityResponse:
      type: object
    GwProfile:
      type: object
    GwProfileResponse:
      type: object
    Uptime:
      type: object
    TimeInfo:
      type: object
    Inventory:
      type: object
    Versions:
      type: object
    RadioUnitCapabilities:
      type: object
    AntennaCapabilities:
      type: object
