openapi: 3.0.0
info:
  version: 0.0.7
  title: LoRaWAN GW Interface
  description: LoRaWAN NS-GW_Interface, GW Interface
  
paths:
  /c:
    put:
      description: Configuration updates from NS to GW.
      requestBody:
        description: |
          list of objects to be updated. If the object is not present, it SHALL be created. 
          the list SHALL be processed in the order of the objects in the list.
          If an error occurs during the processing of an obeject, the processing is aborted.
        required: true
        content:
          application/octet-stream:
            schema:
              $ref: '#/components/schemas/ObjectsPutableToDeviceConfiguration'
          application/json:
            schema: 
              $ref: '#/components/schemas/ObjectsPutableToDeviceConfiguration'
      responses:
        '202':
          description: Objects have been updated.
        '400':
          description: Bad Request.
  /o:
    get:
      description: Get a list of objects the NS MAY retrieve from the GW.
      parameters:
        - $ref: '#/components/parameters/qOption'
        - $ref: '#/components/parameters/fOption'
      responses:
        '205':
          description: |
            Successful return of requested Objects or ObjectIndex etc...
          content:
            application/octet-stream:
              schema:
                oneOf:
                - $ref: '#/components/schemas/ObjectsGetableFromDeviceObjects'
                - $ref: '#/components/schemas/ObjectIndexList'
        '400':
          description: Bad Request.
        '401':
          description: Unauthorized.
        '402':
          description: Bad Option.
        '403':
          description: Object not found, response won't fit in MTU.
  /o/{objectIdPath}:
    get:
      description: Get a list of objects the NS MAY retrieve from the GW.
      parameters:
        - $ref: '#/components/parameters/objectIdPath'
        - $ref: '#/components/parameters/qOption'
        - $ref: '#/components/parameters/fOption'
      responses:
        '205':
          description: |
            Successful return of requested Objects or ObjectIndex etc...
          content:
            application/octet-stream:
              schema:
                oneOf:
                - $ref: '#/components/schemas/ObjectsGetableFromDeviceObjects'
        '400':
          description: Bad Request.
        '401':
          description: Unauthorized.
        '402':
          description: Bad Option.
        '403':
          description: Object not found, response won't fit in MTU.
  
  /d: #d for Delete
    delete:
      description: toDo
      responses:
        '202': 
          description: successfull de-registration; GW is in commissioned state now
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/GwIdentityResponse'
        '400':
          description: De-Registrering at GW failed.          
      
      
components:
  parameters:
    qOption:
      description: |
        q option is a list of object ID which should be retrieved.
        If the q option is not set, the GW will return the list of object IDs it supports. 
      in: query
      name: q
      required: false
      schema:
        type: object
        description: |
          list of requested objectIDs
    fOption:
      description: |
        If the f option (f for full_table) is set to true on requests from NS to GW, the GW will retrieve full table content, 
        while leaving the F option or setting it to FALSE will only retrieve the table ID, label and version
      in: query
      name: f
      required: false
      schema:
        type: boolean
        description: default is false.
    objectIdPath:
      description: Path param specifying Obj
      in: path
      name: objectIdPath
      required: true
      schema: 
        type: integer
    
    
  schemas:
    ObjectsPutableToDeviceConfiguration:
      description: toDo
      anyOf:
        - $ref: '#/components/schemas/RegionOfOperationConfig'
        - $ref: '#/components/schemas/RadioUnits'
        - $ref: '#/components/schemas/Antennas'
        - $ref: '#/components/schemas/DataRateTableConfig'
        - $ref: '#/components/schemas/ChannelConfiguration'
    ObjectsGetableFromDeviceObjects:
      description: toDo
      anyOf:
        - $ref: '#/components/schemas/GwIdentity'
        - $ref: '#/components/schemas/GwProfile'
        - $ref: '#/components/schemas/Uptime'
        - $ref: '#/components/schemas/Versions'
        - $ref: '#/components/schemas/Inventory'
        - $ref: '#/components/schemas/RegionOfOperationConfig'
        - $ref: '#/components/schemas/RadioUnits'
        - $ref: '#/components/schemas/Antennas'
        - $ref: '#/components/schemas/DataRateTableConfig'
        - $ref: '#/components/schemas/ChannelConfiguration'
    ObjectIndexList:
      description: List of object index
      type: object
    Any:
      #placeholder for further work 
      type: object
    Success:
      type: object
    Failure:
      type: object
    GwIdentity:
      type: object
    GwIdentityResponse:
      type: object
    GwProfile:
      type: object
    Uptime:
      type: object
    Versions:
      type: object
    Inventory:
      type: object
    RegionOfOperationConfig:
      type: object
    RadioUnits:
      type: object
    Antennas:
      type: object
    DataRateTableConfig:
      type: object
    ChannelConfiguration:
      type: object
