#****************************************************
# The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
# "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and
# "OPTIONAL" in this document are to be interpreted as described in BCP
# 14 [RFC2119] [RFC8174] when, and only when, they appear in all
# capitals
#****************************************************

openapi: 3.0.0
info:
  version: 0.0.7
  title: LoRaWAN NS-GW NS dataplane interface
  description: LoRaWAN NS-GW dataplane, NS Interface

paths:
  /{gwEui}/u:
    description: uplinks resource of NS dataplane
    parameters:
    - $ref: '#/components/parameters/gwEui'
    post:
      description: |
        Uplinks are POSTed from GW to NS to the /u resource. UPlink post are NOT acknowledged.
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              $ref: '#/components/schemas/ObjectsPostableToNsUplinks'
          application/json:
            schema:
              $ref: '#/components/schemas/ObjectsPostableToNsUplinks'        
      responses:
        '100':
          description: No response is sent if there is no problem at NS
        '400':
          description: Error message are responded, if there is a problem at the NS
  /{gwEui}/ack:
    description: Downlink acknowledgement messages are sent asynchronously, as separete post message
    parameters:
    - $ref: '#/components/parameters/gwEui'
    post:
      description: |
        Acknowledgement messages for downlinks.
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              $ref: '#/components/schemas/ObjectsPostableToNsAcknowledgement'
          application/json:
            schema:
              $ref: '#/components/schemas/ObjectsPostableToNsAcknowledgement'        
      responses:
        '202':
          description: Success.
        '400':
          description: Error message are responded, if there is a problem at the NS  
  /{gwEui}/f:
    description: fine time stamps (fts) if sent indemendenty of the uplink payload
    parameters:
    - $ref: '#/components/parameters/gwEui'
    post:
      description: |
        Fine Time Staps (fts) are POSTed from GW to NS or another server to the /f resource. FTSs post are NOT acknowledged.
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              $ref: '#/components/schemas/ObjectsPostableToNsFts'
          application/json:
            schema:
              $ref: '#/components/schemas/ObjectsPostableToNsFts'        
      responses:
        '100':
          description: No response is sent if there are no problems.
        '400':
          description: Error message are responded, if there is a problem at the NS
components:
  parameters:
    gwEui:
      name: gwEui
      in: path
      required: true
      schema:
        type: integer
      description: todo
  schemas:
    ObjectsPostableToNsUplinks:
      description: |
        the payload MAY contain one or more objects representing an uplink.
        multiple uplinks MAY be used, it the GW internal buffer was used
        for storing "late" uplinks
      anyOf:
      - $ref: '#/components/schemas/Uplink'
    ObjectsPostableToNsFts:
      description: |
        One or multiple fine time stamp infos MAY be sent to the NS or external solver.
      anyOf:
      - $ref: '#/components/schemas/UplinkFineTimestamps'
    ObjectsPostableToNsAcknowledgement:
      description: |
        toDo
      anyOf:
      - $ref: '#/components/schemas/DownlinkAcknowledgement'
    Uplink:
      type: object
    UplinkFineTimestamps:
      type: object
    DownlinkAcknowledgement:
      type: object