#****************************************************
# The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
# "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and
# "OPTIONAL" in this document are to be interpreted as described in BCP
# 14 [RFC2119] [RFC8174] when, and only when, they appear in all
# capitals
#****************************************************

openapi: 3.0.0
info:
  version: 0.0.7
  title: LoRaWAN NS-GW GW dataplane interface
  description: LoRaWAN NS-GW dataplane, GW Interface

paths:
  /d:
    post:
      description: resource for downlinks
      requestBody:
        description: |
          Downlink
        required: true
        content:
          application/octet-stream:
            schema:
              $ref: '#/components/schemas/ObjectsPostableToDownlink'
          application/json:
            schema:
              $ref: '#/components/schemas/ObjectsPostableToDownlink'
      responses:
        '100':
          description: success, but acknowledgment is sent in a separate message.
components:
  schemas:
    ObjectsPostableToDownlink:
      description: toDo
      oneOf:
        - $ref: '#/components/schemas/ClassADownlink'
        - $ref: '#/components/schemas/ClassBUnicast'
        - $ref: '#/components/schemas/ClassCUnicast'
        - $ref: '#/components/schemas/ClassBAndCMulticast'

    ClassADownlink:
      type: object
    ClassBUnicast:
      type: object
    ClassCUnicast:
      type: object
    ClassBAndCMulticast:
      type: object
#    DownlinkAcknowledgement:
#      type: object
